### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by goldyfruit** [redhat-cip/hardware#117]
Seems to have an issue with Python 3 during the HP SmartArray detection.
I'm running Debian 10, no issue with MegaCLI.
```
root@debian:~# hardware-detect 
/bin/sh: 1: cli64: not found
Info: detect_areca: No controller found
Traceback (most recent call last):
  File "/usr/local/bin/hardware-detect", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/hardware/detect.py", line 962, in main
    detect_hpa(hrdw)
  File "/usr/local/lib/python3.7/dist-packages/hardware/detect.py", line 82, in detect_hpa
    if not cli.launch():
  File "/usr/local/lib/python3.7/dist-packages/hardware/hpacucli.py", line 216, in launch
    self.process.expect(PROMPT_REGEXP)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 293, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a string pattern on a bytes-like object
```

```
root@debian:~# pip show hardware
Name: hardware
Version: 0.22.0
Summary: Hardware detection and classification utilities
Home-page: https://github.com/redhat-cip/hardware
Author: eNovance
Author-email: licensing@enovance.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/dist-packages
Requires: ipaddress, Babel, pbr, netaddr, pandas, numpy, six, pexpect
Required-by: 
```

```
root@debian:~# python -V
Python 3.7.3
```

**Comment by goldyfruit** [comment]
Fixed by this commit: https://github.com/redhat-cip/hardware/commit/e13889afd2f35f472be702d8dcf30ed1e613fc58
Not released yet on PyPi.

Sorry for the noise.
