### ISSUE TITLE
hardware-detect fails with python3

### ISSUE THREAD

**Issue by amoralej** [redhat-cip/hardware#48]
Running hardware-detect with python3 fails with following error:

Traceback (most recent call last):
  File "/bin/hardware-detect", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 900, in main
    _main(options)
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 829, in _main
    detect_disks(hrdw)
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 323, in detect_disks
    detect_utils.read_SMART(hw_lst, "/dev/%s" % name)
  File "/usr/lib/python3.6/site-packages/hardware/detect_utils.py", line 353, in read_SMART
    if (line.startswith("Device does not support SMART") or
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

Taking a look into the code, the same issue will be found in several places over detect_utils.py.

**Comment by elfosardo** [comment]
Python 3.x is more (correctly?) strict in differentiating between literal and byte string.
I've uploaded a patch that  should help with that specific issue, although more work may be needed in other parts of the module.
