### ISSUE TITLE
hardware-detect fails on ppc64le due to KeyError

### ISSUE THREAD

**Issue by tbreeds** [redhat-cip/hardware#80]
Vendor ID isn't in the lscpu output:
```
[root@ibm-p9wr-13 ~]# LANG=en_US.UTF-8 lscpu -x
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              144
On-line CPU(s) mask: ffffffffffffffffffffffffffffffffffff
Thread(s) per core:  4
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        6
Model:               2.2 (pvr 004e 1202)
Model name:          POWER9, altivec supported
CPU max MHz:         3800.0000
CPU min MHz:         2300.0000
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            10240K
NUMA node0 CPU(s):   ffffffffffffffffff
NUMA node8 CPU(s):   ffffffffffffffffff000000000000000000
NUMA node252 CPU(s): 0
NUMA node253 CPU(s): 0
NUMA node254 CPU(s): 0
NUMA node255 CPU(s): 0
```
Which causes
```
[root@ibm-p9wr-13 ~]# hardware-detect
/bin/sh: cli64: command not found
Info: detect_areca: No controller found
Cannot find megacli on the system
read_smart: Reading S.M.A.R.T information on /dev/sdb
read_smart_ata: Found S.M.A.R.T information on /dev/sdb
read_smart: Reading S.M.A.R.T information on /dev/sda
read_smart_ata: Found S.M.A.R.T information on /dev/sda
connect: Connection refused 
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
connect: Connection refused
Failed to connect to lldpad - clif_open: Connection refused
Traceback (most recent call last):
  File "/usr/bin/hardware-detect", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 997, in main
    _main(options)
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 924, in _main
    if not detect_system(hrdw):
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 666, in detect_system
    get_cpus(hw_lst)
  File "/usr/lib/python3.6/site-packages/hardware/detect.py", line 725, in get_cpus
    processor), 'vendor', lscpu['Vendor ID']))
KeyError: 'Vendor ID'
[root@ibm-p9wr-13 ~]# 
```

**Comment by tbreeds** [comment]
I clearly messed something up as I expected the merge of https://github.com/redhat-cip/hardware/pull/81 to close this
